### PR TITLE
[KRACOEUS-8622] remove location overrides from KC

### PR DESCRIPTION
**Pull request by bsmith83**

### CODE REVIEW

**Comment by gathreya** [comment]
You've made sure this works after the rice upgrade right?

**Comment by gathreya** [comment]
@tdurkin should we take this in?

**Comment by tdurkin** [comment]
Do we still have to fake-out Remote mode be setting it to Local for embedded to work?

**Comment by gathreya** [comment]
we should not have to after the rice upgrade. I have not checked. @bsmith83 can you?

**Comment by leoherbie** [comment]
we should merge this if we can

**Comment by bsmith83** [comment]
As far as I can tell it works but Im not sure where you guys were using these views, going directly to the lookup manually works for looking up

**Comment by bsmith83** [comment]
I dont know what this means "Do we still have to fake-out Remote mode be setting it to Local for embedded to work?"

**Comment by bsmith83** [comment]
I also noticed a small typo that persisted from the copy paste from the original files into rice, postal code lookup says county lookup in the header.  This is how you guys had it before though.

**Comment by leoherbie** [comment]
I dont know what this means "Do we still have to fake-out Remote mode be setting it to Local for embedded to work?"

No we should not have to fake things out.  We do need to confirm this in our environment config.  I'm going to merge this for now and we can verify things in the morning.

**Pull request merged**
