### PR TITLE
KRACOEUS-8593 removing old help files, adding in 6.0 kns help, and mergi...

### PR DESCRIPTION
**Pull request by jhulslander**
...ng in 6.0 PD help, and fixing merge related issues

### CODE REVIEW

**Comment by jhulslander** [comment]
This PR deletes all the old help content, then puts in kns 6.0 help files, then merges in 6.0 pd help files, and then fixes merging issues to try and get the two to work together correctly

**Comment by leoherbie** [comment]
looks like Check PR is failing trying to parse imagine files.  weird.

**Comment by jhulslander** [comment]
What should I do?

**Comment by blackcathacker** [comment]
Its finding crlf(the bad newlines) in the images, but since they are binary that should be fine.

**Comment by blackcathacker** [comment]
I think I'm ok with this, but want to confirm that we aren't growing the size of the project signficantly with any of these files. Working on test this now.

**Comment by blackcathacker** [comment]
Looks clean as far as newlines and only appears to grow the size of the repo by about 20MB.

**Comment by jhulslander** [comment]
Thanks @blackcathacker Was there something I should have done differently concerning the images?  How did you get the 20MB size difference?  I'm just curious.

**Pull request merged**
