### PR TITLE
[KRAFDBCK-12386] Disabled hard error on save for inactive Sponsors in IP...

### PR DESCRIPTION
**Pull request by rojlarge**
..., and replaced with an audit warning.

This code change provides a solution to the problem of trying to edit IPs with Sponsors that have been inactivated since the IP was first approved, by replacing the hard save error with an audit warning instead.

### CODE REVIEW

**Comment by gathreya** [comment]
needs to be rebased.

**Comment by leoherbie** [comment]
This contrib has been accepted however it wont be rebased and merged in the contrib branch.  It will be available in our next release.

**Comment by vikinzer** [comment]
I've been testing the items contributed by IU in KC-QA-Research as they've been merged.  Do you have a sense of when this will be available in the KCo QA environment for validation?

**Comment by leoherbie** [comment]
maybe tomorrow.

**Comment by vikinzer** [comment]
Awesome.  I'll set a reminder and check for the change for the next couple days to complete testing.

**Pull request closed without merging**
