### PR TITLE
KRACOEUS-8760:moved version and sql info to footer

### PR DESCRIPTION
**Pull request by jwillia**
per @blackcathacker request moved version and sql version to footer

### CODE REVIEW

**Comment by jwillia** [comment]
footerversion

**Comment by blackcathacker** [comment]
Much better than in the header. Not sure about the positioning though. Maybe smaller text below and centered? I think we are finished with 6.0 in any case so this will probably be first thing in 6.0.1.

**Comment by gathreya** [comment]
test this please.

**Comment by jwillia** [comment]
footer2
updated to place on bottom

**Comment by leoherbie** [comment]
why does it say NO VERSION?

**Comment by jwillia** [comment]
thats what the version is set to in the config
<param name="build.version" override="false">NO VERSION</param>

**Comment by leoherbie** [comment]
I see.  ok

**Pull request merged**
