### PR TITLE
KRACOEUS-8453: Closing dialog window through document actions

### PR DESCRIPTION
**Pull request by jamey-rsmart**

### CODE REVIEW

**Comment by jamey-rsmart** [comment]
@blackcathacker, discussed your suggestion for the simplified buttons with Victor and he likes it.  The only problem is that while the Rolodex maint doc that is currently used is the old KNS version, changing the KRAD footer here will change it globally. If the maint docs are ever to be switched over to KRAD, the Rolodex maint doc will have only two buttons.  This begs the question, is this even a concern anymore with the state of KRAD and KC moving forward?

**Comment by blackcathacker** [comment]
First, no. Second, if we ever do move the Rolodex to using KRAD we can create a new KRAD maint doc view for the typical case and another for this one. So either way, you should be fine to make this custom maint doc work specifically for inline adding.

**Comment by jamey-rsmart** [comment]
Made changes and rebased.

**Comment by blackcathacker** [comment]
Looks much better. Thanks!

**Pull request merged**
