### PR TITLE
KRACOEUS-8702 no longer auto-searching with empty criteria on search lin...

### PR DESCRIPTION
**Pull request by jhulslander**
...ks

### CODE REVIEW

**Comment by gathreya** [comment]
As chris mentioned, a few of these lookups that search on click are intentional. You did verify with 5.2.1 code right?

**Comment by jhulslander** [comment]
I double checked, no auto-searches turned off in this PR were auto-searches on dly.

**Comment by gathreya** [comment]
Sweet, thanks

**Comment by gathreya** [comment]
Typo on search in quite a few places and you changed start to search in a few too?

**Comment by jhulslander** [comment]
Huh this is weird. Something weird is going on. The weird riffs weren't on my branch. I'll check it out in the am.

**Comment by jhulslander** [comment]
OK, I don't know what happened with the last merge (funk stuff), but this looks correct now.

**Pull request merged**
