### PR TITLE
KULRICE-14086 -  Ajax disclosure triangles.

### PR DESCRIPTION
**Pull request by se10**
Work-around to get Ajax working with disclosure triangles.  Initial page load is much faster, although disclosure triangles initially render as closed.  (Not sure if this is a user experience issue.)

### CODE REVIEW

**Comment by kualiCoeusCi** [comment]
Can one of the admins verify this patch?

**Comment by leoherbie** [comment]
this PR needs to be rebased

**Comment by leoherbie** [comment]
I'm guessing that this PR includes a lot of changes copied from rice components.   If this is true which parts of the code contains the customizations?

**Comment by se10** [comment]
Will rebase.

The work-around is considered temporary.  According to Brian Smith, the actual fix will mostly likely reside in Rice.  (Brian and I paired on this.  He has a better understanding of the larger problem, and can elaborate.)

On the Skype call today (with Doug, Jerry and Claus), Doug asked that a pull request be done with the work-around, to see how the Key Personnel page responded with working Ajax disclosure triangles, knowing further mods would be required for a fix, and the part lifted (and currently copied) from Rice would go away.

The change lifted from the Rice component is small, and in KcCollectionGroupBase.java, lines 272 - 276, where a special case is handled.  (Brian can elaborate)

**Comment by se10** [comment]
Rebased.  Removed conflict in ProposalPersonnelPage.xml.

**Comment by se10** [comment]
Actually... hold off on merging this.  (It has been a bad afternoon :)

**Comment by se10** [comment]
Okay.  Conflict error fixed.  (Sorry for the delay.)

**Comment by blackcathacker** [comment]
Is there a reason you didn't just extend CollectionGroupBase instead of copying the whole class into KC? Looks like you'll copy some methods over, but is there something that is incompatible with that?

**Comment by blackcathacker** [comment]
test this please

**Comment by se10** [comment]
As mentioned in yesterday's meeting, what is there is not an actual solution, and is instead a "snapshot of a search mission" to see if Ajax'd disclosure triangles could be made to work, and some timings could be done for comparison.  There is currently redundant code, which was copy/pasted during the experimentation.  Ajax'd disclosure triangles do work with this mod, but consider it an intermediate step to decide if they should be sued.

Jerry and Doug felt it would be worth pulling this in to trunk, to try it out.  If it is decided to use Ajax disclosure triangles, an actual solution would be implemented, which would likely require modification to Rice/KRAD, and possibly a KRAD custom component used in KC.  Brian can best speak to this, as he paired with me on this case, and supplied the KRAD expertise which made the current progress possible.  (It was pretty cool to watch him work this case.  He really knows his way around KRAD internals!)

**Pull request merged**
